Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -37,10 +37,17 @@ jobs:
           echo "::set-output name=changed_files::${changed_files}"
       - name: Determine the target branch
         run: |
-           # Get the branch name from the ref
-             target_branch="${GITHUB_REF#refs/heads/}"
-             echo "Target Branch: $target_branch"
-        shell: bash
+               # Get the branch name from the ref
+                target_branch="${{ github.ref }}"
+                target_branch="${target_branch#refs/heads/}"
+
+                if [ -z "$target_branch" ]; then
+                     echo "Error: Could not determine the target branch. Exiting..."
+                     exit 1
+                fi
+
+                echo "Target Branch: $target_branch"
+                shell: bash
 
       - name: Create Target Directory
         run: mkdir -p "$target_branch"
