Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -6,26 +6,53 @@ on:
       - devops_code  # Change this to your main branch name if it's different
     paths:
       - '**.py'
+
 jobs:
-  build:
+  pylint:
     runs-on: ubuntu-22.04
     strategy:
       matrix:
         python-version: ["3.10.4"]
     steps:
-    - uses: actions/checkout@v3
-    - name: Set up Python ${{ matrix.python-version }}
-      uses: actions/setup-python@v3
-      with:
-        python-version: ${{ matrix.python-version }}
-    - name: Install dependencies
-      run: |
-        python -m pip install --upgrade pip
-        pip install pylint
-    - name: Analysing the code with pylint
-      run: |
-        pylint $(git ls-files '*.py')
+      - name: Checkout Code
+        uses: actions/checkout@v3
 
-     
-       
-  
+      - name: Set up Python ${{ matrix.python-version }}
+        uses: actions/setup-python@v3
+        with:
+          python-version: ${{ matrix.python-version }}
+
+      - name: Install dependencies
+        run: |
+          python -m pip install --upgrade pip
+          pip install pylint
+
+      - name: Determine changed Python files
+        id: changed_files
+        run: |
+          changed_files=($(git diff --name-only origin/devops_code...HEAD | grep '\.py$'))
+          echo "::set-output name=changed_files::${changed_files[@]}"
+
+      - name: Run Pylint on changed files
+        id: pylint_check
+        run: |
+          changed_files=(${{ steps.changed_files.outputs.changed_files }})
+
+          pylint_fail=false
+
+          for file in "${changed_files[@]}"; do
+            pylint "$file" > "$file.pylintrc" || true
+            pylint_score=$(grep -oP '(?<=Your code has been rated at ).*(?=/10)' "$file.pylintrc")
+
+            if (( $(echo "$pylint_score < 6" | bc -l) )); then
+              echo "Pylint score is less than 6 for $file. Aborting."
+              pylint_fail=true
+            else
+              echo "Pylint score for $file: $pylint_score"
+            fi
+          done
+
+          if [ "$pylint_fail" = true ]; then
+            echo "::set-output name=fail::true"
+            exit 1
+          fi
