Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -16,7 +16,7 @@ jobs:
     - name: Set up Python
       uses: actions/setup-python@v2
       with:
-        python-version: 3.10  # Specify your Python version here
+        python-version: 3.9  # Specify your Python version here
 
     - name: Install Dependencies
       run: pip install pylint PyGithub markdown
@@ -26,10 +26,14 @@ jobs:
         pylint factorial.py > pylint_report.txt
         pylint_score=$(grep 'Your code has been rated at' pylint_report.txt | awk '{print $7}')
         echo "Pylint Score: $pylint_score"
+        if (( $(bc <<< "$pylint_score < 6") )); then
+          echo "Pylint score is less than 6. Workflow failed."
+          exit 1
+        fi
         echo "::set-output name=score_float::${pylint_score}"
 
     - name: Commit and Push if Pylint Score > 6
-      if: ${{ steps.pylint.outputs.score_float > 6 }}
+      if: ${{ success() }}
       run: |
         token=${{ secrets.GITHUB_TOKEN }}
         git config user.name "GitHub Actions"
@@ -41,7 +45,7 @@ jobs:
         echo "Committed and pushed to GitHub."
 
     - name: Create Markdown Report
-      if: ${{ steps.pylint.outputs.score_float > 6 }}
+      if: ${{ success() }}
       run: |
         echo "## Pylint Score: $pylint_score" > pylint_report.md
         cat pylint_report.txt >> pylint_report.md
@@ -49,7 +53,7 @@ jobs:
         echo "::set-output name=markdown_report::pylint_report.md"
 
     - name: Upload Markdown Report
-      if: ${{ steps.pylint.outputs.score_float > 6 }}
+      if: ${{ success() }}
       uses: actions/upload-artifact@v2
       with:
         name: pylint-report
